# The west manifest file for upstream Zephyr module OMX.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# This imports the latest upstream Zephyr manifest file.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.
#
# Beginning with west 0.8, the following command-line options
# can be used to initialize with a repository lacking a west.yml
# file at the top level.
#
#   west init
#     -m <repository>
#     --mr <branch_name>
#     --mf <manifest_pathname>
#     <workspace>

manifest:
  version: 0.9

  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: git@github.com:zephyrproject-rtos


  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: master
      import: true
